version: "3.9"

services:
  postgresDB:
    image: postgres:latest
    container_name: trackingDB
    restart: always
    environment:
      POSTGRES_DB: trackingDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432
